import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import SideNav from '@/components/SideNav'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/utils/SessionProvider'
import { Toaster } from '@/components/ui/toaster'

// Remove loading from uploadthing
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { extractRouterConfig } from 'uploadthing/server'
import { ourFileRouter } from './api/uploadthing/core'
//

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <SessionProvider session={session}>
          <Header />
          <SideNav />
          <div>{children}</div>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  )
}
